services:
  mqtt:
    image: eclipse-mosquitto:2-openssl
    restart: always
    ports:
      - "9883:9883"
      - "8883:8883"
      - "1883:1883"
    expose: [1883,8883,9883]
    volumes:
      - ./.docker/mosquitto/config:/mosquitto/config
      - ./.docker/mosquitto/data:/mosquitto/data
      - ./.docker/mosquitto/log:/mosquitto/log
      - ./.docker/mosquitto/certs:/mosquitto/certs
      - ./.docker/mosquitto/passwords:/mosquitto/passwords
    network_mode: bridge
  httpd:
    image: inuitviking/rockyhttpd:2.4.51-aarch64
    restart: always
    ports:
      - "80:80"
      - "443:443"
    expose: [80,443]
    volumes:
      - ./.docker/httpd/conf/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./.docker/httpd/conf.d/infoscreen.conf:/etc/httpd/conf.d/infoscreen.conf
      - ./.docker/httpd/certs:/etc/httpd/certs
      - ./.docker/httpd/log:/var/log/httpd
      - ./www:/var/www
    network_mode: bridge
  mqtt-client:
    image: inuitviking/lpos-mqtt-client:0.0.1-aarch64
    restart: always
    depends_on:
      mqtt:
        condition: service_started
    volumes:
      - ./.docker/mosquitto/certs/ca-root-cert.crt:/usr/src/mqtt-client/certs/ca-root-cert.crt
      - ./misc/mqtt.csv:/usr/src/mqtt-client/mqtt.csv
  comet:
    image: inuitviking/lpos-comet:0.0.1-aarch64
    restart: always
    ports:
      - "8080:8080"
    expose: [8080]
    depends_on:
      mqtt-client:
        condition: service_started
    volumes:
      - ./misc/mqtt.csv:/usr/src/comet/mqtt.csv
